DEBUG 2019-11-03 23:37:13.299 UTC: 	 Running on: Linux login01.hep.wisc.edu 4.4.178-1.el7.elrepo.x86_64 #1 SMP Wed Apr 3 05:46:30 EDT 2019 x86_64 x86_64 x86_64 GNU/Linux
Description:	CentOS Linux release 7.6.1810 (Core) 

DEBUG 2019-11-03 23:37:13.299 UTC: 	 Executing command: 'submit'
DEBUG 2019-11-03 23:37:13.300 UTC: 	 Found CRAB cache file /afs/hep.wisc.edu/home/vshang/.crab3
DEBUG 2019-11-03 23:37:13.305 UTC: 	 Checking credentials
DEBUG 2019-11-03 23:37:13.306 UTC: 	 Found proxy file /tmp/x509up_u10060
DEBUG 2019-11-03 23:37:13.306 UTC: 	 Getting proxy life time left
DEBUG 2019-11-03 23:37:13.408 UTC: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u10060 -timeleft
 output : 603736

 error: 
 retcode : 0
DEBUG 2019-11-03 23:37:13.512 UTC: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u10060 -actimeleft
 output : 603736

 error: 
 retcode : 0
DEBUG 2019-11-03 23:37:13.512 UTC: 	 Proxy valid for 167:42:16 hours
INFO 2019-11-03 23:37:13.512 UTC: 	 Will use CRAB configuration file crab_cfg.py
DEBUG 2019-11-03 23:37:13.512 UTC: 	 Loading CRAB configuration file.
ERROR 2019-11-03 23:37:13.768 UTC: 	 Invalid CRAB configuration: Parameter Data.whitelist is not known.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
ERROR 2019-11-03 23:37:13.769 UTC: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1910.patch2/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1910.patch2/bin/crab", line 145, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1910.patch2/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1910.patch2/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 305, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1910.patch2/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 93, in loadConfig
    raise ConfigurationException(configmsg)
ConfigurationException: Invalid CRAB configuration: Parameter Data.whitelist is not known.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
DEBUG 2019-11-03 23:39:51.956 UTC: 	 Running on: Linux login01.hep.wisc.edu 4.4.178-1.el7.elrepo.x86_64 #1 SMP Wed Apr 3 05:46:30 EDT 2019 x86_64 x86_64 x86_64 GNU/Linux
Description:	CentOS Linux release 7.6.1810 (Core) 

DEBUG 2019-11-03 23:39:51.957 UTC: 	 Executing command: 'submit'
DEBUG 2019-11-03 23:39:51.957 UTC: 	 Found CRAB cache file /afs/hep.wisc.edu/home/vshang/.crab3
DEBUG 2019-11-03 23:39:51.963 UTC: 	 Checking credentials
DEBUG 2019-11-03 23:39:51.963 UTC: 	 Found proxy file /tmp/x509up_u10060
DEBUG 2019-11-03 23:39:51.963 UTC: 	 Getting proxy life time left
DEBUG 2019-11-03 23:39:52.066 UTC: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u10060 -timeleft
 output : 603578

 error: 
 retcode : 0
DEBUG 2019-11-03 23:39:52.170 UTC: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u10060 -actimeleft
 output : 603577

 error: 
 retcode : 0
DEBUG 2019-11-03 23:39:52.170 UTC: 	 Proxy lifetime 603578 secs is different from voms extension lifetime 603577 secs for proxy: /tmp/x509up_u10060
DEBUG 2019-11-03 23:39:52.170 UTC: 	 Proxy valid for 167:39:37 hours
INFO 2019-11-03 23:39:52.170 UTC: 	 Will use CRAB configuration file crab_cfg.py
DEBUG 2019-11-03 23:39:52.170 UTC: 	 Loading CRAB configuration file.
DEBUG 2019-11-03 23:39:52.174 UTC: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2019-11-03 23:39:52.175 UTC: 	 Working area '/afs/hep.wisc.edu/user/vshang/public/tDM_nanoAOD/CMSSW_10_2_9/src/PhysicsTools/NanoAODTools/crab/crab_20191103_preselectSR' already exists 
Please change the requestName in the config file
ERROR 2019-11-03 23:39:52.175 UTC: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1910.patch2/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1910.patch2/bin/crab", line 145, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1910.patch2/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1910.patch2/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 309, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1910.patch2/lib/python2.7/site-packages/CRABClient/ClientUtilities.py", line 413, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/afs/hep.wisc.edu/user/vshang/public/tDM_nanoAOD/CMSSW_10_2_9/src/PhysicsTools/NanoAODTools/crab/crab_20191103_preselectSR' already exists 
Please change the requestName in the config file
DEBUG 2019-11-04 01:47:36.205 UTC: 	 Running on: Linux login01.hep.wisc.edu 4.4.178-1.el7.elrepo.x86_64 #1 SMP Wed Apr 3 05:46:30 EDT 2019 x86_64 x86_64 x86_64 GNU/Linux
Description:	CentOS Linux release 7.6.1810 (Core) 

DEBUG 2019-11-04 01:47:36.206 UTC: 	 Executing command: 'submit'
DEBUG 2019-11-04 01:47:36.206 UTC: 	 Found CRAB cache file /afs/hep.wisc.edu/home/vshang/.crab3
DEBUG 2019-11-04 01:47:36.214 UTC: 	 Checking credentials
DEBUG 2019-11-04 01:47:36.215 UTC: 	 Found proxy file /tmp/x509up_u10060
DEBUG 2019-11-04 01:47:36.215 UTC: 	 Getting proxy life time left
DEBUG 2019-11-04 01:47:36.321 UTC: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u10060 -timeleft
 output : 604301

 error: 
 retcode : 0
DEBUG 2019-11-04 01:47:36.425 UTC: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u10060 -actimeleft
 output : 604300

 error: 
 retcode : 0
DEBUG 2019-11-04 01:47:36.425 UTC: 	 Proxy lifetime 604301 secs is different from voms extension lifetime 604300 secs for proxy: /tmp/x509up_u10060
DEBUG 2019-11-04 01:47:36.425 UTC: 	 Proxy valid for 167:51:40 hours
INFO 2019-11-04 01:47:36.425 UTC: 	 Will use CRAB configuration file crab_cfg.py
DEBUG 2019-11-04 01:47:36.426 UTC: 	 Loading CRAB configuration file.
DEBUG 2019-11-04 01:47:36.460 UTC: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2019-11-04 01:47:36.460 UTC: 	 Working area '/afs/hep.wisc.edu/user/vshang/public/tDM_nanoAOD/CMSSW_10_2_9/src/PhysicsTools/NanoAODTools/crab/crab_20191103_preselectSR' already exists 
Please change the requestName in the config file
ERROR 2019-11-04 01:47:36.461 UTC: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1910.patch2/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1910.patch2/bin/crab", line 145, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1910.patch2/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1910.patch2/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 309, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1910.patch2/lib/python2.7/site-packages/CRABClient/ClientUtilities.py", line 413, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/afs/hep.wisc.edu/user/vshang/public/tDM_nanoAOD/CMSSW_10_2_9/src/PhysicsTools/NanoAODTools/crab/crab_20191103_preselectSR' already exists 
Please change the requestName in the config file
DEBUG 2019-11-04 02:56:04.907 UTC: 	 Running on: Linux login01.hep.wisc.edu 4.4.178-1.el7.elrepo.x86_64 #1 SMP Wed Apr 3 05:46:30 EDT 2019 x86_64 x86_64 x86_64 GNU/Linux
Description:	CentOS Linux release 7.6.1810 (Core) 

DEBUG 2019-11-04 02:56:04.908 UTC: 	 Executing command: 'submit'
DEBUG 2019-11-04 02:56:04.908 UTC: 	 Found CRAB cache file /afs/hep.wisc.edu/home/vshang/.crab3
DEBUG 2019-11-04 02:56:04.914 UTC: 	 Checking credentials
DEBUG 2019-11-04 02:56:04.914 UTC: 	 Found proxy file /tmp/x509up_u10060
DEBUG 2019-11-04 02:56:04.914 UTC: 	 Getting proxy life time left
DEBUG 2019-11-04 02:56:05.019 UTC: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u10060 -timeleft
 output : 600193

 error: 
 retcode : 0
DEBUG 2019-11-04 02:56:05.123 UTC: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u10060 -actimeleft
 output : 600191

 error: 
 retcode : 0
DEBUG 2019-11-04 02:56:05.123 UTC: 	 Proxy lifetime 600193 secs is different from voms extension lifetime 600191 secs for proxy: /tmp/x509up_u10060
DEBUG 2019-11-04 02:56:05.123 UTC: 	 Proxy valid for 166:43:11 hours
INFO 2019-11-04 02:56:05.124 UTC: 	 Will use CRAB configuration file crab_cfg.py
DEBUG 2019-11-04 02:56:05.124 UTC: 	 Loading CRAB configuration file.
DEBUG 2019-11-04 02:56:05.128 UTC: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2019-11-04 02:56:05.129 UTC: 	 Working area '/afs/hep.wisc.edu/user/vshang/public/tDM_nanoAOD/CMSSW_10_2_9/src/PhysicsTools/NanoAODTools/crab/crab_20191103_preselectSR' already exists 
Please change the requestName in the config file
ERROR 2019-11-04 02:56:05.129 UTC: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1910.patch2/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1910.patch2/bin/crab", line 145, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1910.patch2/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1910.patch2/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 309, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1910.patch2/lib/python2.7/site-packages/CRABClient/ClientUtilities.py", line 413, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/afs/hep.wisc.edu/user/vshang/public/tDM_nanoAOD/CMSSW_10_2_9/src/PhysicsTools/NanoAODTools/crab/crab_20191103_preselectSR' already exists 
Please change the requestName in the config file
DEBUG 2019-11-04 09:08:53.583 UTC: 	 Running on: Linux login01.hep.wisc.edu 4.4.178-1.el7.elrepo.x86_64 #1 SMP Wed Apr 3 05:46:30 EDT 2019 x86_64 x86_64 x86_64 GNU/Linux
Description:	CentOS Linux release 7.6.1810 (Core) 

DEBUG 2019-11-04 09:08:53.584 UTC: 	 Executing command: 'status'
DEBUG 2019-11-04 09:08:53.584 UTC: 	 Found CRAB cache file /afs/hep.wisc.edu/home/vshang/.crab3
ERROR 2019-11-04 09:08:53.585 UTC: 	 Error: crab_20191103_test/ is not a valid CRAB project directory.
ERROR 2019-11-04 09:08:53.585 UTC: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1910.patch2/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1910.patch2/bin/crab", line 145, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1910.patch2/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 40, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1910.patch2/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 262, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1910.patch2/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 580, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: crab_20191103_test/ is not a valid CRAB project directory.
DEBUG 2019-11-04 17:33:50.394 UTC: 	 Running on: Linux login01.hep.wisc.edu 4.4.178-1.el7.elrepo.x86_64 #1 SMP Wed Apr 3 05:46:30 EDT 2019 x86_64 x86_64 x86_64 GNU/Linux
Description:	CentOS Linux release 7.6.1810 (Core) 

DEBUG 2019-11-04 17:33:50.394 UTC: 	 Executing command: 'status'
DEBUG 2019-11-04 17:33:50.395 UTC: 	 Found CRAB cache file /afs/hep.wisc.edu/home/vshang/.crab3
ERROR 2019-11-04 17:33:50.395 UTC: 	 Error: crab_20191103_test1/ is not a valid CRAB project directory.
ERROR 2019-11-04 17:33:50.396 UTC: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1910.patch2/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1910.patch2/bin/crab", line 145, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1910.patch2/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 40, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1910.patch2/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 262, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1910.patch2/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 580, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: crab_20191103_test1/ is not a valid CRAB project directory.
DEBUG 2019-11-05 04:20:15.323 UTC: 	 Running on: Linux login01.hep.wisc.edu 4.4.178-1.el7.elrepo.x86_64 #1 SMP Wed Apr 3 05:46:30 EDT 2019 x86_64 x86_64 x86_64 GNU/Linux
Description:	CentOS Linux release 7.6.1810 (Core) 

DEBUG 2019-11-05 04:20:15.323 UTC: 	 Executing command: 'status'
DEBUG 2019-11-05 04:20:15.323 UTC: 	 Found CRAB cache file /afs/hep.wisc.edu/home/vshang/.crab3
ERROR 2019-11-05 04:20:15.324 UTC: 	 Error: crab_20191103_preselect1/ is not a valid CRAB project directory.
ERROR 2019-11-05 04:20:15.324 UTC: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1910.patch2/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1910.patch2/bin/crab", line 145, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1910.patch2/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 40, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1910.patch2/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 262, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1910.patch2/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 580, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: crab_20191103_preselect1/ is not a valid CRAB project directory.
DEBUG 2019-11-05 05:42:16.270 UTC: 	 Running on: Linux login01.hep.wisc.edu 4.4.178-1.el7.elrepo.x86_64 #1 SMP Wed Apr 3 05:46:30 EDT 2019 x86_64 x86_64 x86_64 GNU/Linux
Description:	CentOS Linux release 7.6.1810 (Core) 

DEBUG 2019-11-05 05:42:16.270 UTC: 	 Executing command: 'status'
DEBUG 2019-11-05 05:42:16.270 UTC: 	 Found CRAB cache file /afs/hep.wisc.edu/home/vshang/.crab3
ERROR 2019-11-05 05:42:16.271 UTC: 	 Error: crab_20191103_preselect1/ is not a valid CRAB project directory.
ERROR 2019-11-05 05:42:16.271 UTC: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1910.patch2/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1910.patch2/bin/crab", line 145, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1910.patch2/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 40, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1910.patch2/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 262, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1910.patch2/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 580, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: crab_20191103_preselect1/ is not a valid CRAB project directory.
DEBUG 2019-11-07 01:58:16.743 UTC: 	 Running on: Linux login01.hep.wisc.edu 4.4.178-1.el7.elrepo.x86_64 #1 SMP Wed Apr 3 05:46:30 EDT 2019 x86_64 x86_64 x86_64 GNU/Linux
Description:	CentOS Linux release 7.6.1810 (Core) 

DEBUG 2019-11-07 01:58:16.743 UTC: 	 Executing command: 'status'
DEBUG 2019-11-07 01:58:16.743 UTC: 	 Found CRAB cache file /afs/hep.wisc.edu/home/vshang/.crab3
ERROR 2019-11-07 01:58:16.744 UTC: 	 Cannot find .requestcache file in CRAB project directory /afs/hep.wisc.edu/user/vshang/public/tDM_nanoAOD/CMSSW_10_2_9/src/PhysicsTools/NanoAODTools/crab/Test_5/crab_TTWJetsToLNu
ERROR 2019-11-07 01:58:16.744 UTC: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1910.patch2/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1910.patch2/bin/crab", line 145, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1910.patch2/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 40, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1910.patch2/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 262, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1910.patch2/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 584, in validateOptions
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1910.patch2/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 446, in loadLocalCache
    raise ex
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /afs/hep.wisc.edu/user/vshang/public/tDM_nanoAOD/CMSSW_10_2_9/src/PhysicsTools/NanoAODTools/crab/Test_5/crab_TTWJetsToLNu
DEBUG 2019-11-07 02:12:48.352 UTC: 	 Running on: Linux login01.hep.wisc.edu 4.4.178-1.el7.elrepo.x86_64 #1 SMP Wed Apr 3 05:46:30 EDT 2019 x86_64 x86_64 x86_64 GNU/Linux
Description:	CentOS Linux release 7.6.1810 (Core) 

DEBUG 2019-11-07 02:12:48.352 UTC: 	 Executing command: 'status'
DEBUG 2019-11-07 02:12:48.353 UTC: 	 Found CRAB cache file /afs/hep.wisc.edu/home/vshang/.crab3
ERROR 2019-11-07 02:12:48.354 UTC: 	 Cannot find .requestcache file in CRAB project directory /afs/hep.wisc.edu/user/vshang/public/tDM_nanoAOD/CMSSW_10_2_9/src/PhysicsTools/NanoAODTools/crab/Test_5/crab_TTWJetsToLNu
ERROR 2019-11-07 02:12:48.354 UTC: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1910.patch2/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1910.patch2/bin/crab", line 145, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1910.patch2/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 40, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1910.patch2/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 262, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1910.patch2/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 584, in validateOptions
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1910.patch2/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 446, in loadLocalCache
    raise ex
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /afs/hep.wisc.edu/user/vshang/public/tDM_nanoAOD/CMSSW_10_2_9/src/PhysicsTools/NanoAODTools/crab/Test_5/crab_TTWJetsToLNu
DEBUG 2019-11-07 03:05:31.537 UTC: 	 Running on: Linux login01.hep.wisc.edu 4.4.178-1.el7.elrepo.x86_64 #1 SMP Wed Apr 3 05:46:30 EDT 2019 x86_64 x86_64 x86_64 GNU/Linux
Description:	CentOS Linux release 7.6.1810 (Core) 

DEBUG 2019-11-07 03:05:31.538 UTC: 	 Executing command: 'getlog'
DEBUG 2019-11-07 03:05:31.538 UTC: 	 Found CRAB cache file /afs/hep.wisc.edu/home/vshang/.crab3
DEBUG 2019-11-07 06:12:12.684 UTC: 	 Running on: Linux login01.hep.wisc.edu 4.4.178-1.el7.elrepo.x86_64 #1 SMP Wed Apr 3 05:46:30 EDT 2019 x86_64 x86_64 x86_64 GNU/Linux
Description:	CentOS Linux release 7.6.1810 (Core) 

DEBUG 2019-11-07 06:12:12.684 UTC: 	 Executing command: 'submit'
DEBUG 2019-11-07 06:12:12.692 UTC: 	 Found CRAB cache file /afs/hep.wisc.edu/home/vshang/.crab3
DEBUG 2019-11-07 06:12:12.697 UTC: 	 Checking credentials
DEBUG 2019-11-07 06:12:12.698 UTC: 	 Found proxy file /tmp/x509up_u10060
DEBUG 2019-11-07 06:12:12.698 UTC: 	 Getting proxy life time left
DEBUG 2019-11-07 06:12:12.800 UTC: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u10060 -timeleft
 output : 329225

 error: 
 retcode : 0
DEBUG 2019-11-07 06:12:12.904 UTC: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u10060 -actimeleft
 output : 329224

 error: 
 retcode : 0
DEBUG 2019-11-07 06:12:12.904 UTC: 	 Proxy lifetime 329225 secs is different from voms extension lifetime 329224 secs for proxy: /tmp/x509up_u10060
DEBUG 2019-11-07 06:12:12.904 UTC: 	 Proxy valid for 91:27:04 hours
DEBUG 2019-11-07 06:12:12.905 UTC: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
DEBUG 2019-11-07 08:57:36.209 UTC: 	 Running on: Linux login01.hep.wisc.edu 4.4.178-1.el7.elrepo.x86_64 #1 SMP Wed Apr 3 05:46:30 EDT 2019 x86_64 x86_64 x86_64 GNU/Linux
Description:	CentOS Linux release 7.6.1810 (Core) 

DEBUG 2019-11-07 08:57:36.209 UTC: 	 Executing command: 'submit'
DEBUG 2019-11-07 08:57:36.217 UTC: 	 Found CRAB cache file /afs/hep.wisc.edu/home/vshang/.crab3
DEBUG 2019-11-07 08:57:36.222 UTC: 	 Checking credentials
DEBUG 2019-11-07 08:57:36.223 UTC: 	 Found proxy file /tmp/x509up_u10060
DEBUG 2019-11-07 08:57:36.223 UTC: 	 Getting proxy life time left
DEBUG 2019-11-07 08:57:36.326 UTC: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u10060 -timeleft
 output : 319301

 error: 
 retcode : 0
DEBUG 2019-11-07 08:57:36.429 UTC: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u10060 -actimeleft
 output : 319300

 error: 
 retcode : 0
DEBUG 2019-11-07 08:57:36.429 UTC: 	 Proxy lifetime 319301 secs is different from voms extension lifetime 319300 secs for proxy: /tmp/x509up_u10060
DEBUG 2019-11-07 08:57:36.429 UTC: 	 Proxy valid for 88:41:40 hours
DEBUG 2019-11-07 08:57:36.430 UTC: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
